version: '3.8'

services:
  # 1. Reverse Proxy (Gateway)
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"   # Tambahkan baris ini! Agar bisa diakses via http://localhost
      - "443:443" # UNTUK NANTI DI VPS
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - ai_network
    depends_on:
      - frontend

 # 2. Frontend Web (Aplikasi Python kamu)
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    # === TAMBAHKAN DI SINI (BAGIAN START) ===
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb  # Mapping folder USB Host ke Container
    # === TAMBAHKAN DI SINI (BAGIAN END) ===
    environment:
      - OPENAI_API_KEY=os.getenv("OPENAI_API_KEY") # Pastikan sintaks ini benar di environment
      - VECTOR_DB_URL=http://vector-db:8000
    networks:
      - ai_network
    restart: always

  # 3. Vector Database (ChromaDB)
  vector-db:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/chroma/data
    networks:
      - ai_network
    # Port tidak di-expose ke publik, hanya bisa diakses oleh 'frontend'

networks:
  ai_network:
    driver: bridge